version: '3.8'

services:
  bookstore-api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api-automation
    environment:
      - API_BASE_URL=${API_BASE_URL:-https://fakerestapi.azurewebsites.net}
      - PARALLEL_THREADS=${PARALLEL_THREADS:-3}
      - TEST_SUITE=${TEST_SUITE:-testng.xml}
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./target/allure-report:/app/target/allure-report
    command: ["run-tests"]
